arch_package_manager = "paru"

flatpak_default_systemwide = false

# Whether to use the [hostname_groups] config table to decide which
# group files to use or to use all files in the groups folder.
# Default: false
hostname_groups_enabled = true

# Which group files apply for which hostnames
# paths starting without a / are relative to the groups folder
# Default: None
[hostname_groups]
john-desktop = ["default"]
john-laptop = ["default"]
server = []
